### ISSUE TITLE
add force-watch mode

### ISSUE THREAD

**Issue by ymasory** [pennmem/Penn-TotalRecall#23]
Instead of forcing listening to entire file, it would be nice to only force looking at entire file. This should work even if file is pre-annotated by pywr. In this mode switching between annotations causes a high speed "scroll" to the new location, forcing you to at least see the waveform in between.

**Comment by krishnancr** [comment]
The force watch is partially implemented where in you can pan from one annotation to another if you've not watched/reached the target annotation as yet. One an annotation has been watched/reached, you can no more pan "to" that annotation. In such a case you can jump from an annotation to another. You can also stop an annotation in between when it is panning. From the point you have stopped you can either play or continue panning to the next annotation. 
- Pan to finish has not been implemented 
- The speed of panning is not done using a multiplier but instead is hard coded 
- If you stop a pan in between and go back to the previous annotation. Now if you try to pan to the next annotation , it jumps instead of panning.

**Comment by ymasory** [comment]
Patrick and Mike have agreed a screen-forward action is preferable to smooth panning.
